# Generated by Django 5.1.7 on 2025-03-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusage',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('apps', models.JSONField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.computer')),
            ],
        ),
    ]
